### ISSUE TITLE
Question: How to Ask Users to "Allow Contract to Spend Tokens On Your Behalf"

### ISSUE THREAD

**Issue by Flora258** [PatrickAlphaC/full-stack-web3-metamask-connectors#1]
Hi, Mr. Collins,

I don't have any issues thus far with this repo, but I just had a question. I've been watching your tutorial on "how to connect your smart contract to your frontend in 6 different ways", and I was wondering how I could ask the users to approve a contract to spend their tokens, using the JS that I've typed so far. This is my code (your code, really):

```
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {useState} from "react";
import {ethers} from "ethers";

export default function Home() {
  const [isConnected, setIsConnected] = useState(false);
  const [provider, setProvider] = useState();
  async function connect() {
    if (typeof window.ethereum !== "undefined") {
      try {
        await ethereum.request({method: "eth_requestAccounts"});
        setIsConnected(true);
        let connectedProvider = new ethers.providers.Web3Provider(window.ethereum);
        setSigner(connectedProvider.getSigner());
      } catch(e) {
        console.log(e);
      } 
    } else {
      setIsConnected(false);
    }
  }

  async function approve() {
    if (typeof window.ethereum !== "undefined") {
      const contractAddress = "...";
      const abi = [...];
      const connectedProvider = new ethers.providers.Web3Provider(window.ethereum);
      const signer = connectedProvider.getSigner();
      const contract = new ethers.Contract(contractAddress, abi, signer);
      try {
        await contract.approve();
      } catch (error) {
        console.log(error);
      }
    } else {
      console.log("Please install MetaMask");
    }
  }
    return(<div className={styles.container}>Hello, user! {isConnected
    ? ("You're connected!") : (<button onClick= {() => connect()}>Connect!</button>)}
    {isConnected ? <button onClick={() => approve()}>Approve</button> : ""}
    </div>);
}

```
I just want to have it like most swaps (I'm not making a swap) where they ask you to approve their spending your tokens before you actually spend anything. When I click "approve" on my localhost, nothing happens. What am I doing wrong?

Thanks!

**Comment by PatrickAlphaC** [comment]
Assuming your `abi` and `address` are correct, almost...

```
await contract.approve();
```

^^ This function takes 2 parameters:

```
function approve(address _spender, uint256 _value) public returns (bool success)
```

So you'd have to add the `spender` and the `value`. See the [ETH docs](https://ethereum.org/en/developers/docs/standards/tokens/erc-20/) for more on erc20 tokens.

Closing for now.

**Comment by Flora258** [comment]
Thanks for the help, I'll let you know if I can get it to work.

**Comment by Flora258** [comment]
So I took your advice today, and I finally got the approve transaction to show up! Thanks for helping me out, @PatrickAlphaC, I'm sort of a newbie dev, so I was super frustrated all last week trying to figure this out. Thank you!
